### ISSUE TITLE
Harmony 2.0

### ISSUE THREAD

**Issue by purpleorangegames** [BepInEx/BepInEx#102]
I read a lot about Harmony on their discord server and it seems Harmony 2.0 isn't ready for use yet, did you try asking the author about it?

**Comment by denikson** [comment]
Greetings!

I'm not sure what's the issue here. Harmony 2 is indeed still in development, but the main API for patching is more or less set in stone as far as we are aware. For us it simply means that whenever Harmony 2 is out, porting existing plugins won't be an issue.

Even so, BepInEx with Harmony 2 has been tested since RC1 on multiple games without any issues. Whenever Harmony 2 will get an official release, we will start using that.

If you have any BepInEx 4 plugins, consider either upgrading them to BepInEx 5 or use [BepInEx.BepInEx4Upgrader](https://github.com/BepInEx/BepInEx.BepInEx4Upgrader) to automatically shim BepInEx 4 plugins to BepInEx 5 (and thus shim Harmony 1 to work with Harmony 2).

I'm closing this issue for now. If there are any other concerns, feel free to elaborate, and I'll reopen this issue.
