### ISSUE TITLE
Patcher entrypoint does not work as expected

### ISSUE THREAD

**Issue by kohanis** [BepInEx/BepInEx#116]
Patcher breaks games ui.
Green Hell and Subnautica Below Zero here, for example https://imgur.com/a/20NMBaT
Any interaction locked. Was used clear steam versions and artifacts 5.0.1.194, 5.0.1.188 and 5.0.1.186
Green Hell - Unity 2019.3.9 / Game 1.5.4
Subnautica Below Zero - Unity 2019.2.17 / Game Apr-2020 27520 (last stable, early access, nevermind)

**Comment by denikson** [comment]
Greetings!

Could you be more specific? What do you mean by "patcher method"? Do you get any errors? Have you tried the stable version of BepInEx first?
Do you have any `preloader_error` log files in the game directory?
Could you post your latest BepInEx log (located in `BepInEx/LogOutput.txt`?

A quick test with latest Green Hell on Steam (v. 1.5.4, build 9627) and latest stable BepInEx (v.5.0.1) works just fine:

![image](https://user-images.githubusercontent.com/13762037/81145762-99130300-8f7f-11ea-971e-cdb7e21896b8.png)
(added RuntimeUnityEditor plugin to test that plugins work as well)

Haven't tested Subnautica yet, but given a rather similar Unity version I'd assume it works as well.

In future, please use the issue template we provide, as it helps you help us by collecting the important information we can use to actually debug the problem.

**Comment by kohanis** [comment]
Patcher method in sense patching assembly, not through UnityDoorstop
Thought to use this for dev

**Comment by denikson** [comment]
If you are going to use BepInEx, I first suggest to just install it and make sure it runs on the game.  
Since you're going to develop a patcher, I suggest enabling BepInEx console by going to `BepInEx/config/BepInEx.cfg` and setting `Enabled` under the `Logging.Console` section to `true`.
That should open up a log console when you run the game and should display any potential errors.

First, try simply running BepInEx without any patchers/plugins and make sure it does actually work (like in the screenshot I posted). If there are errors, delete all of BepInEx (along with Doorstop's `winhttp.dll` and its config) and reinstall it. 
If there are still errors, you can copy the text from the console (or again, get the `BepInEx/LogOutput.txt` -- yes it should generate if you installed BepInEx correctly).

As a last resort, you can try to obtain the game's output log by setting `redirectOutputLog=true` in `doorstop_config.ini`. This should generate `output_log.txt` into the game's folder when you run the game.

Finally, refer to [the guide on writing preloader patchers](https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/preloader_patchers.html) on how to do proper assembly patching with it. Note that preloader patcher is often rather overkill and you might be better off writing [a normal BepInEx plugin](https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/plugin_tutorial/index.html) and using [Harmony](https://harmony.pardeike.net/articles/intro.html) to patch methods during runtime.

**Comment by denikson** [comment]
> Patcher method in sense patching assembly, not through UnityDoorstop

Wait, you mean the hardpatcher (the .EXE that patches BepInEx into the game permanently instead of using the normal build)?

**Comment by kohanis** [comment]
Yeah, to debug with dnspy

**Comment by bbepis** [comment]
The patcher entrypoint is deprecated and has only been kept around due to potential uses in native Linux and Mac OSX where UnityDoorstop does not function.

As for your specific use case, the UnityDoorstop method works when debugging, however the method slightly changes depending on what you want to debug with dnSpy.

The guide in the BepInEx wiki is outdated (as it was written for 4.0), and a more up to date version can be read here: https://github.com/risk-of-thunder/R2Wiki/wiki/Debugging-Your-Mods-With-dnSpy

Keep in mind it was made for Risk of Rain 2 in mind, and will be slightly different for your usecase. For example, you will need to download debug binaries for the specific unity version of the game you are attempting to debug with.

If all you want is to debug a plugin, then you can ignore the `Debugging patched assemblies` section in the guide.
However if you do intend to debug assemblies that were edited via preloader patchers, then you need to follow the instructions in that section too.

**Comment by denikson** [comment]
Closing this issue owing to inactivity. The games have been tested to work on BepInEx 5.1 without issues, and the [new debugging guide](https://bepinex.github.io/bepinex_docs/master/articles/advanced/debug/plugins_dnSpy.html) should prove useful for debugging games using 5.1.

If you do encounter any problems with 5.1, please create a new issue.
