### ISSUE TITLE
Unable to build proper BEPIN plugin targeting NET 3.5

### ISSUE THREAD

**Issue by Kein** [BepInEx/BepInEx#135]
I have a project on Unity 2018.3.6.
The player **executable** and **UnityPlayer** library are x64 compatible.
**mscorlib.dll** reports normal x86 lib and is 2.0.x
**Assembly-CSharp.dll** reports normal x86 lib

The docs say:
https://bepinex.github.io/bepinex_docs/master/articles/dev_guide/plugin_tutorial/1_setup.html

> Different Unity may require you to use different .NET Framework versions. As a rule of thumb, you can use .NET Framework 3.5 in all Unity games, but you will get the least API available. In order to determine the exact version of .NET Framework to use, check the file version of mscorlib.dll in <GameName>_Data\Managed folder: if it's 4.0.0.0 or newer, you can target .NET Framework 4.x (usually 4.6).
> 
> Note
> It is possible to target both .NET Framework and .NET Standard games by using .NET Framework 3.5 as the build target.
> 

However that does not appears to be correct. If I'm targeting .NET 3.0/3.5 and add to references compatible UnityEngine.dll, UnityEngine.CoreModule.dll and BepInEx.dll then the project simply wont build in Visual Studio. If I try to build it by hand via MSBuild:
```
d:\Programs\VisualStudio2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3258: The primary reference "UnityEngine" could not be resolved because it has an indirect dependency on the .NET Framework assembly "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which has a higher version "4.0.0.0"
than the version "2.0.0.0" in the current target framework. [d:\Unlinked\MVS2017\repos\Bepitest\Bepitest\Bepitest.csproj]
```

However, because of **mscorlib.dll** being 2.x i cant resolve it by targeting framework 4.x because in this case, while the library builds just fine and loaded by Bepi just fine, Unity managed environment cannot resolve types from it and fails with error: 
```
[Unity Log] TypeLoadException: Could not load type "MyTest" from assembly "Bepitest"
```

```cs
public class MyTest: CustomPluginClassThatTheGameUses
{
	public MyTest()
	{
             //blah
        }
}
```

When I try to feed the API instance of the custom class on bepi's gameobject Awake it just fails with type resolution, which is usually indication of misconfigured references of dependencies.

**Comment by bbepis** [comment]
Can you try creating a new project that targets `.NET Standard 2.0`, and creating a BepInEx plugin with that?

**Comment by Kein** [comment]
I could but to what purpose? The Unity project in question does not have support for netstandard, it uses old stable mono, not the `bleeding edge`.

**Comment by bbepis** [comment]
The difference between "stable" and bleeding edge mono is a bit blurry in later Unity versions. Typically .NET Standard support is indicated by the presence of `netstandard.dll` rather than the version of Mono / mscorlib, as the versioning of both is very inconsistent.

If you're not able to get that working either, then you can try this alternative:

https://cdn.discordapp.com/attachments/623910091132895232/713293967546122240/un.zip
Download this .zip file, and instead of referencing the UnityEngine and etc. libraries in Managed, reference these instead. They have their references fixed so that you're able to link against them correctly in .NET 3.5 projects.

This issue stems from the fact that the version of mscorlib that ships with certain versions of Unity mismatch with the UnityEngine libraries that are also shipped referencing a different version of mscorlib.

**Comment by Kein** [comment]
Alright I've build the netstandard one, the issue is now different but to no suprise:
```
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
Stack trace:
UnityEngine.SceneManagement.SceneManager.Internal_ActiveSceneChanged (Scene previousActiveScene, Scene newActiveScene)
```

**Comment by bbepis** [comment]
The target version only matters for compilation. At runtime, mono just loads dependencies regardless of version, and if there's no API mismatch then you don't get any execution errors. Hence why referencing a modified .dll at compilation time works

**Comment by Kein** [comment]
Hmm, not really sure I get it.

> The target version only matters for compilation.

Okay, but the it does not explain why do I get typeloader issues runtime if I target .NETFX 4.0? It compiles just fine and Bepi loads plugin fine and executes code fine, but custom type just not available for unity managed environment. If, as you say, * target version only matters for compilation* then I shouldnt have any aforementioned:
`[Unity Log] TypeLoadException: Could not load type "MyTest" from assembly "Bepitest"`
 issues here, no?

**Comment by denikson** [comment]
> Okay, but the it does not explain why do I get typeloader issues runtime if I target .NETFX 4.0? 

This is more of an issue with the mono runtime and how that game is packaged. 

We have encountered a similar with the similar setup before, namely Bug Fables. In it the version of `mscorlib.dll` is `2.0.0.0` while `UnityEngine.dll` and all of its modules reference `mscorlib.dll` version `4.0.0.0`.  
However, because of how mono works and how UnityEngine DLLs make use of `mscorlib` classes, there is no problematic code that causes mono to actually check for version matching. I don't think anyone researched the real reason, but in simple words, the version of mono runtime used in Unity 2018.x seems to have a mind of its own when it comes to caring about version matching. 

For instance, it's fine to reference `mscorlib` version `4.0.0.0` and use some of its methods, but using any of `System.Func` causes mono to check for matched

**Comment by Kein** [comment]
> the version of mono runtime used in Unity 2018.x seems to have a mind of its own

Ooh, I see, so it is 2018 specific issue. Fair enough, thanks. Weird tho.

**Comment by bbepis** [comment]
I simplified my answer a bit; the true reason is related to the way that the type resolver for the CLR works.

When the runtime attempts to JIT compile a .NET method, when resolving any referenced types in the method it will actually search the current AppDomain for the type first, and if it can't find it it will then load the assembly from disk.

For example, say you have a type called `MyNamespace.MyType` in both `AssemblyA` and `AssemblyB`.
You have a plugin that references `AssemblyB`, and has a method that calls `MyNamespace.MyType.MyMethod()`.

If `AssemblyA` has been loaded into the AppDomain already, and the method you're executing references `MyNamespace.MyType.MyMethod()`, the CLR will just use the method from `AssemblyA` instead of loading it from `AssemblyB` as you expect since it scanned the AppDomain for the type regardless of what assembly the class originated from.


This quirk with the CLR is what enables preloader patches in BepInEx in the first place; patching an assembly from the Managed directory and loading it into the AppDomain will cause all references to the assembly to use the modified one in memory instead of the one in the Managed folder.

When your plugin is first loaded and executed, `UnityEngine` w/ mscorlib 4.0.0.0 has already been loaded into the AppDomain. Even though your plugin references a non-existent `UnityEngine` w/ mscorlib 2.0.0.0, the CLR will never attempt to load it since all the types it wants has already been provided by the assembly that has previously been loaded.

------------

As for why the plugin fails to work when compiled with .NET 4.x, we don't know the specific reason behind it. Keep in mind that when Unity compiles a game with a .NET version, it specifically says `.NET 2.0/4.0 subset` instead of the framework outright. Mono itself doesn't supply a full/compliant implementation of .NET 4.x; it only has enough components implemented and working correctly that normal circumstances would work without issues.

Horse mentioned one of the known failure points with this; System.Func<> seems to be implemented somewhat differently within regular .NET Framework and Unity's Mono library.
We don't know what specifically is different or broken, but whenever your plugin contains a lambda and Mono attempts to load it, it crashes as it seems to not be able to use implementation-specific things that the C# compiler adds behind the scenes relating to compiled lambdas and Func<>.

**Comment by Kein** [comment]
> If AssemblyA has been loaded into the AppDomain already, and the method you're executing references MyNamespace.MyType.MyMethod(), the CLR will just use the method from AssemblyA instead of loading it from AssemblyB as you expect since it scanned the AppDomain for the type regardless of what assembly the class originated from.

Yes, that I  understand. What was weird is that the Type was unique so it should have searched AssemblyB, no?

I know that mono isnt strictly compliant with netfx, but I specifically stripped down whole thing just to contain bare type class that complies to the requirement of the asset the project uses. It didnt even come down to the quirks of Func or any other delegates/aspects, it just straight didnt see the type despite the fact rest of plugin logic that sued Unity API executed flawlessly.

Anyway, the compiled libraries you provided seems to work fine, hopefully it just Unity 2018.x branch being dumb so it is not gonna be common issue.

**Comment by Kein** [comment]
I'm gonna use this thread instead of making new one.

Got another weird bug, 2017.4.4, **mscorlib.dll** 2.0 and the rest of the dependencies report Runtime: v2.0.50727
I've used .NET 3.5 class lib template. 
Issue is that Harmony does not see any method at all. For example
```cs
var harmony = new Harmony("org.bepinex.plugins.test1");
//remote method in game Assembly
var original = typeof(PlatformCharacterInput).GetMethod("Awake"); 
//local method plugin in the plugin
var post = typeof(MyPlugin).GetMethod("AttachGO");
```

both returned as `null`. This is impossible?

**Comment by Bluscream** [comment]
> The difference between "stable" and bleeding edge mono is a bit blurry in later Unity versions. Typically .NET Standard support is indicated by the presence of `netstandard.dll` rather than the version of Mono / mscorlib, as the versioning of both is very inconsistent.
> 
> If you're not able to get that working either, then you can try this alternative:
> 
> https://cdn.discordapp.com/attachments/623910091132895232/713293967546122240/un.zip Download this .zip file, and instead of referencing the UnityEngine and etc. libraries in Managed, reference these instead. They have their references fixed so that you're able to link against them correctly in .NET 3.5 projects.
> 
> This issue stems from the fact that the version of mscorlib that ships with certain versions of Unity mismatch with the UnityEngine libraries that are also shipped referencing a different version of mscorlib.

How did you generate these? I need one for a specific assembly-csharp
