### ISSUE TITLE
BepInEx 5.3 fails in games that bundle their own Mono.Cecil

### ISSUE THREAD

**Issue by ag2s20150909** [BepInEx/BepInEx#148]
**Describe the bug**
not work

**To Reproduce**

**Expected behavior**

**Screenshots and logs**
[preloader_20201103_163305_289.log](https://github.com/BepInEx/BepInEx/files/5480060/preloader_20201103_163305_289.log)

**Desktop (please complete the following information):**
 - Game and game version : Vikings Daughter v0.23.0 Viking - Win x64
 - BepInEx version : BepInEx_x64_5.3.0.0

**Additional context**

**Comment by denikson** [comment]
Greetings!

Thank you for the information! This is a known issue in BepInEx 5.3 in some rare cases. This game contains the following assemblies in its `Vikings Daughter_Data\Managed` folder:

* `Mono.Cecil.dll`
* `Mono.Cecil.Mdb.dll`
* `Mono.Cecil.Pdb.dll`

These DLLs currently conflict with BepInEx 5.3 which includes its own (newer) versions of them. This issue if fixed in Bleeding Edge builds.

You can fix this in two ways:

1. Use the latest Bleeding Edge build from https://builds.bepis.io/projects/bepinex_be
2. Remove the above mentioned DLLs from `Vikings Daughter_Data\Managed` folder (or better, move them out of the game folder altogether and keep for backup). In that case the game will use the DLLs provided by BepInEx 5.3 instead.

**Comment by denikson** [comment]
Fix now released as part of 5.4, closing.
