### ISSUE TITLE
Preloader fails on the spot.

### ISSUE THREAD

**Issue by Woodensponge** [BepInEx/BepInEx#150]
**Describe the bug**

Preloader fails to initiate, most likely due to .NET Framework version differences.

**To Reproduce**

I installed BepInEx for a game called ULTRAKILL. I followed all the instructions on this website provided in the readme accordingly (https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-win) and used the latest BepInEx version (5.3.0.0). I then installed ConfigurationManager. Keep in mind the same logs appear when ConfigurationManager is uninstalled.

**Expected behavior**

I expected ConfigurationManager to bring up a GUI when pressing F1.

**Screenshots and logs**

[output_log.txt](https://github.com/BepInEx/BepInEx/files/5488610/output_log.txt)
[preloader_20201104_101249_344.log](https://github.com/BepInEx/BepInEx/files/5488611/preloader_20201104_101249_344.log)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: ULTRAKILL (Patch 2020/10/13)
 - BepInEx version [e.g. 4.0]: 5.3.0.0

**Additional context**

While taking a peek at dnspy at both Assembly-CSharp.dll and BepInEx.dll, I noticed that ULTRAKILL used .NET Framework 4 while BepInEx.dll used 3.5

![image](https://user-images.githubusercontent.com/43834352/98129910-ac981b80-1e87-11eb-9bef-c75ddf0a84fb.png)

![image](https://user-images.githubusercontent.com/43834352/98129956-b91c7400-1e87-11eb-9dd4-5a1468a4cc61.png)

This could be causing the issue.
I'm also relatively new to BepInEx. I've tried browsing the internet to see what's going on, but I found next to nothing. Help would be appreciated.

**Comment by Woodensponge** [comment]
Uh, I've looked into the issues a bit more and decided to click on the issue currently labeled "not work."
It's exactly the problem I'm facing at the moment.

Here's the link.
https://github.com/BepInEx/BepInEx/issues/148#issue-735126401

**Comment by denikson** [comment]
Greetings!

Thank you for providing the information.

On a quick glance the error logs in #148 doesn't match the logs you have. As such, I daresay the problems are likely unrelated. I renamed that issue to have a more descriptive name (and to remove the implication of there not being a fix).

That said, I do suggest maybe trying the latest Bleeding Edge build first as pointed out in the comment in #148. I'll test the game as soon as I can and get back to this issue if Bleeding Edge build does not work out for you.

**Comment by Woodensponge** [comment]
I did, here it is.
[preloader_20201104_110432_969.log](https://github.com/BepInEx/BepInEx/files/5488943/preloader_20201104_110432_969.log)

Also, the game doesn't have Mono.Cecil.dll in its Managed folder
![image](https://user-images.githubusercontent.com/43834352/98135359-bb81cc80-1e8d-11eb-9fe7-3d6ab421c45f.png)

**Comment by Woodensponge** [comment]
BepInEx 5.0.1.0 works just fine btw.

**Comment by denikson** [comment]
> Also, the game doesn't have Mono.Cecil.dll in its Managed folder

Thanks for the screenshot! Say, did you have any other mod loaders installed in the game before trying out BepInEx? For some reason you have `MonoMod.RuntimeDetour` and `MonoMod.Utils` which are indicative of some mod loader being installed besides BepInEx. 

I suggest doing the following:

1. Delete the whole `Managed` folder
2. Verify the game file on Steam. This is a pretty straightforward process: [guide on verifying game files on Steam](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335)
3. Wait until Steam redownloads the folder (it should be pretty fast as the `Managed` folder is just a few MBs)
4. Try using BepInEx again (5.3 or Bleeding Edge if you still have it installed).

Also, please screenshot your managed folder again right after you have verified the game files.
I'll install the game myself in a few hours too in order to test it.

**Comment by Woodensponge** [comment]
I have verified the game's files before I began installing BepInEx. Any outstanding files don't interact with the actual game anymore.

**Comment by Woodensponge** [comment]
![image](https://user-images.githubusercontent.com/43834352/98143003-96458c00-1e96-11eb-85a7-8aafa8852d9b.png)
![image](https://user-images.githubusercontent.com/43834352/98143064-a3627b00-1e96-11eb-851c-5d10b55a980f.png)

**Comment by denikson** [comment]
I got the game (latest on Steam -- that is indeed the Oct 13th update) and BepInEx 5.3 works fine:

![ultrakill_ok](https://user-images.githubusercontent.com/13762037/98146723-70d77300-1ed4-11eb-90b4-5a627c874fa7.gif)

Moreover, the default game's `Managed` folder does not have any of MonoMod DLLs (which makes sense since those are mainly used by mod loaders):

![image](https://user-images.githubusercontent.com/13762037/98146891-91073200-1ed4-11eb-974e-5e49221dca8d.png)

This is consistent with the information available one [SteamDB for the game](https://steamdb.info/depot/1229491/): in the list of all the files of the latest game update there are no MonoMod DLLs present.

This leads me to believe that

* You happen to install BepInEx in a way that puts files into `Managed` folder. In that case, please follow [the installation guide](https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-win). When BepInEx is installed correctly, no BepInEx files (MonoMod, Harmony, BepInEx) should be present in `Managed` folder but instead only in a separate BepInEx folder.
* You happen to install something else besides BepInEx (maybe some old mod loader from somewhere?). In that case I'd just delete those two MonoMod DLLs as a quick fix and maybe even reinstall the whole game to make sure there are no excess mod loaders/tools installed.

Of course, this all is based on assumption you did delete `Managed` folder and actually did try to verify the game files right now. The fact that every file in the screenshot is dated to recent date except MonoMod implies even more it's not from the game or BepInEx.

This is indeed a peculiar issue, although it's more related to there being wrong files in the wrong places for reasons currently unknown.

**Comment by Woodensponge** [comment]
Yeah, it works now. Steam for some reason failed the verification check multiple times during troubleshooting, had to reinstall.
![works](https://user-images.githubusercontent.com/43834352/98150371-88930500-1e9c-11eb-9422-498b96cb12f7.gif)

Thank's for the help.
