### ISSUE TITLE
debug framework support

### ISSUE THREAD

**Issue by HanaForward** [BepInEx/BepInEx#159]
if i want to use my framework  to load plug
how to use dnspy debug plug assemblies?
not only possible to debug assemblies loaded via the Assembly-CSharp preloader .

**Comment by denikson** [comment]
Greetings!

BepInEx Docs has extensive info on how to [debug plugins with dnSpy](https://bepinex.github.io/bepinex_docs/master/articles/advanced/debug/plugins_dnSpy.html), [debug plugins with Visual Studio](https://bepinex.github.io/bepinex_docs/master/articles/advanced/debug/plugins_vs.html) and [how to debug assemblies patched with preloader patches via dnSpy](https://bepinex.github.io/bepinex_docs/master/articles/advanced/debug/assemblies_dnSpy.html).

Debugging preloader-patched assemblies requires either changing BepInEx configuration or using dnSpy's module view to load assemblies from memory. The last guide I mentioned outlines the procedure.

**Comment by HanaForward** [comment]
so, if my framework  load assemblies from memory , i can to debug plugins with dnSpy?

**Comment by denikson** [comment]
I'm not sure what your framework is. If framework/plugin you make is based on or is using BepInEx, you can make use of the guides I linked to debug plugins with dnSpy.

The guides I linked are mostly specific for BepInEx or plugins/loaders that use BepInEx as a base. If you use something else to bootstrap into the game than BepInEx, you might want to check out [general dnSpy debugging guide](https://github.com/dnSpy/dnSpy/wiki/Debugging-Unity-Games).

**Comment by HanaForward** [comment]
i am use openmod for my framework , debug plug is very difficult。

**Comment by HanaForward** [comment]
it not on use BepInEx , it was own load your own,
I cannot find it in the dnspy module window，But it does load

**Comment by denikson** [comment]
OpenMod does not use BepInEx as its own base, which means that you're limited to using pure dnSpy approach. You can try using the module view as outlined in [BepInEx debug guide](https://bepinex.github.io/bepinex_docs/master/articles/advanced/debug/assemblies_dnSpy.html#using-dnspys-module-view) but the details depend on how OpenMod itself works.

I'm not sure how you managed to find BepInEx repo while trying to do debugging with OpenMod. I would suggest posting an issue to [OpenMod's own issue tracker](https://github.com/openmod/openmod/issues) if you want direct support regarding debugging their plugins.

As such, I'll close the issue for now since it's not directly related to BepInEx. If you have any issues regarding BepInEx itself, feel free to create a new issue. 
For other quick messages regarding BepInEx or Unity modding I would suggest joining [BepInEx Discord](https://discord.gg/MpFEDAg).
