### ISSUE TITLE
Way to execute a patcher plugin after chain loader runs?

### ISSUE THREAD

**Issue by Dual-Iron** [BepInEx/BepInEx#169]
I have a patcher that attempts to set the base type of a type definition to BaseUnityPlugin. Because BaseUnityPlugin references the unity engine assembly, the chain loader fails afterward. Is there a way to run my patcher after the chainloader runs? Would that even be effective?

**Comment by denikson** [comment]
Greetings!

I'm going to answer on this issue since you closed the last one. My answer is still roughly the same:

BepInEx generally provides two types of patching: runtime patching with HarmonyX and preloader patching with Mono.Cecil.
The core difference is that HarmonyX is works by detouring original method execution to the patched one, while Mono.Cecil allows you to rewrite the original assembly entirely.

The reason why preloader patchers don't give you direct access to patch anything but in `Managed` is because of how preloader patching was designed in general. The purpose of preloader is to modify *game assemblies in-memory* and to *overcome mono's (i.e. the runtime's) assembly resolving order* so as to allow modifying core game assemblies in-memory and have them being loaded without fear of mono forcing load of the original assembly. That way the original assembly isn't affected at all.
Preloader patching itself works on the assumption that assemblies that are patched in-memory reside in `Managed` which is mono's root assembly directory. 

BepInEx itself loads its plugins by first probing them with Cecil in order to detect if there are any plugins to load. Since Cecil isn't able to read assemblies from memory in-memory patching of plugins creates a problem that would need to be solved by a tighter coupling of preloader and chainloader -- something we do not want as two should be able to work separately.

What I instead suggest to do is to abuse preloader patchers a little. We are planning on better preloader patcher layout for BepInEx 6 which does not require you to always patch something, but for the time being you can write a simple empty preloader patcher where you can run any code you want. That would look something like this:

```cs
public static class MyPreloader
{
    public static IEnumerable<string> TargetDLLs { get; } = new string[0]; // Don't request anything

    public static void Patch(AssemblyDefinition ad) {} // Not used since there is nothing to patch

    public static void Initialize()
    {
        // Run any code before assemblies in Managed are patched in-memory
    }

    public static void Finish()
    {
        // You can run any code you want. This is run after assemblies in Managed have been patched in-memory and loaded
    }
}
```

You can then load BepInEx plugins manually into Cecil via `AssemblyDefinition.ReadAssembly(string path)`, do the changes you want and then use `assemblyDefinition.Write()` to write the edited plugin assembly back to the DLL. This way the plugin is edited into the DLL which is a permanent edit (usually more preferred with plugins) that BepInEx chainloader will then see.

You can see a few examples of this trick being used:
* [BepInEx4Upgrader](https://github.com/BepInEx/BepInEx.BepInEx4Upgrader/blob/master/BepInEx.BepInEx4Upgrader/BepIn4Patcher.cs): our own preloader patcher that read all BepInEx 4 plugins and edited them into BepInEx 5 plugins.
* [IPAHarmonyShimmer](https://github.com/BepInEx/IPALoaderX/blob/master/BepInEx.IPAHarmonyShimmer/HarmonyShimmer.cs): reads Illusion Plugin Architecture plugin DLLs, rewrites their references to `0Harmony.dll` and then resaves
* [QModPluginEmulator](https://github.com/SubnauticaModding/QModManager/blob/master/QModPluginEmulator/QModPluginGenerator.cs): takes old-style QModManager plugins and rewrites them to work with new QModManager + BepInEx 5

As for your question of how not to reference `BaseUnityPlugin`, it is purely Cecil question. You're likely trying to use something like
```cs
assemblyDefinition.MainModule.ImportReference(typeof(BaseUnityPlugin))
```
to get the reference to `BaseUnityPlugin`. However, this is just all syntax sugar for adding `BepInEx.dll` reference and constructing `TypeRefence` that matches description of `BaseUnityPlugin`. This can be done manually via Cecil API.

Alternative approach is to load `BepInEx.dll` into cecil as well with `AssemblyDefinition.ReadAssembly`, use `assemblyDefinition.MainModule.GetType(string typeName)` to get `TypeDefinition` to `BaseUnityPlugin` and then pass it to `assemblyDefinition.MainModule.ImportReference(TypeDefinition typeDef)` which will also generate the valid type reference. 

All in all, when using cecil in preloader patchers, you should avoid directly referencing `BaseUnityPlugin` (by direct referencing I mean using something like `typeof(BaseUnityPlugin)` which will cause the runtime to attempt to resolve it and in turn cause to load in `UnityEngine.dll` or `UnityEngine.CoreModule.dll`. You can load assemblies into Cecil though since loading plugins into Cecil will not load them into the runtime. You can even say that Cecil works as some kind of "sandbox" into which you can load any assembly without breaking things.

**Comment by Dual-Iron** [comment]
Thanks! This helped a ton. I'd suggest putting this little workaround where more people can see it, this is really useful information.
