### ISSUE TITLE
BepInEX not load any BepInEX plugin

### ISSUE THREAD

**Issue by kmou424** [BepInEx/BepInEx#178]
**Describe the bug**

BepInEX not load any BepInEX plugin
Seem like BepInxEX was not started

**To Reproduce**

Simplely installed bepinex and run Koikatu.exe

**Expected behavior**

Game starting with mods

**Screenshots and logs**

![image](https://user-images.githubusercontent.com/35911521/107257936-2b4bb880-6a76-11eb-9711-4185a12d6335.png)
Only preloader log,because bupinex is not working
[preloader_20210209_004859_700.log](https://github.com/BepInEx/BepInEx/files/5945321/preloader_20210209_004859_700.log)

**Desktop (please complete the following information):**
 - Game and game version Koikatu 5.1: 
 - BepInEx version 5.4.5.0 (x64): 

**Additional context**

**Comment by denikson** [comment]
Greetings!

Sorry for the late reply, I was meaning to answer you earlier. Thanks for adding a screenshot as it makes now much more sense.

Right now, it seems like your installation is broken. You claim to use BepInEx 5.4.5 but the console claims you have BepInEx 3.1 installed. We do not support such old BepInEx version, and it seems like you have different installations mixed up.

I suggest reinstalling BepInEx from scratch. You might have to manually clean up game files as well since BepInEx 3.1 edits the game files unlike BepInEx 5.

Since you're trying to use BepInEx on Koikatsu, I'm going to close this issue because you're better off seeking help in the game's modding community. Koikatsu community has premade BepInEx plugin packs and installers that can automatically fix your game  (such as the [HFPatch](https://github.com/ManlyMarco/KK-HF_Patch)). I suggest joining [Koikatsu Discord server](https://discord.gg/hevygx6) and asking for technical assistance there.

**Comment by kmou424** [comment]
@denikson thanks bro

**Comment by kmou424** [comment]
> Greetings!
> 
> Sorry for the late reply, I was meaning to answer you earlier. Thanks for adding a screenshot as it makes now much more sense.
> 
> Right now, it seems like your installation is broken. You claim to use BepInEx 5.4.5 but the console claims you have BepInEx 3.1 installed. We do not support such old BepInEx version, and it seems like you have different installations mixed up.
> 
> I suggest reinstalling BepInEx from scratch. You might have to manually clean up game files as well since BepInEx 3.1 edits the game files unlike BepInEx 5.
> 
> Since you're trying to use BepInEx on Koikatsu, I'm going to close this issue because you're better off seeking help in the game's modding community. Koikatsu community has premade BepInEx plugin packs and installers that can automatically fix your game (such as the [HFPatch](https://github.com/ManlyMarco/KK-HF_Patch)). I suggest joining [Koikatsu Discord server](https://discord.gg/hevygx6) and asking for technical assistance there.
> 
> If you have any other new issues or the issue persists, feel free to create a new issue ticket here.

btw, how to update BepInEx 3.1 to BepInEx 5.x?
