### ISSUE TITLE
Doorstop fails to run

### ISSUE THREAD

**Issue by EvaisaGiac** [BepInEx/BepInEx#181]
**Describe the bug**
BepInEx no longer launches all of the sudden.
There was no updates to the game I am trying to use it on and no updates to BepInEx but nothing happens when I launch the game (besides the game launching.)
It works fine for a friend of mine still which makes it even weirder, the only thing I can think of is some weird windows update or something.

**To Reproduce**
Just tried to launch a game with BepInEx installed (properly because it used to work fine)

**Expected behavior**
It should open the console window since that is enabled in the config.

**Screenshots and logs**
There is no console log or preloader log being generated which means that the door stop isn't even working I guess.

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]:  Monster Sanctuary, Build 1.0.1.19
 - BepInEx version [e.g. 4.0]: 5.4.5

**Additional context**
None that I can think of.

**Comment by EvaisaGiac** [comment]
Actually after completely restarting my computer it seems to work fine, I have absolutely no idea what could have caused this.
I reinstalled BepInEx and the game itself multiple times.

**Comment by ghorsington** [comment]
Greetings!

This is a somewhat known issue that appears to be related to how Steam might cause some environment variables to be preserved between runs. Restarting the indeed seems to fix the issue for many people.

At the moment there is no clean fix except the workaround of restarting one's PC. A proper fix/workaround is in the works for next version of BepInEx.

I'm going to close the issue since you managed to already fix it. If you do have any other issues, feel free to create a new issue ticket.
