### ISSUE TITLE
Fallback mod information from AssemblyInfo.cs if no BepInPlugin attribute is given

### ISSUE THREAD

**Issue by Measurity** [BepInEx/BepInEx#189]
**Is your feature request related to a problem? Please describe.**
I would like to reduce redundancy and tedium in project configuration.
The issue with using attributes is that I cannot change those fields at compile time without string replacing the code.

**Describe the solution you'd like**
Take the information required by the BepInEx "ChainLoader" class from the Assembly if it isn't found by the BepInPlugin attribute.
The GUID could also be taken from AssemblyInfo. Example definition: `[assembly: Guid("a4df9f47-b2d9-49a9-b237-09220857c051")]`.

**Describe alternatives you've considered**
 - Adding build step to string replace code files with the right BepInEx metadata.
 - Adding a batch file to rename the plugin metadata.

**Additional context**
It's possible that one solution has multiple BepInEx plugins defined so attribute should still be possible and have priority over AssemblyInfo.

**Improvements and extras**
Generate GUID if not defined by using author+mod name bytes into GUID constructor.

**Comment by js6pak** [comment]
#154

**Comment by ghorsington** [comment]
Greetings!

This is a good ticket in a sense that we have discussed this before but have never really written down our discussions on a public channel.  
It has been a while since we have talked about this, so I will try to summarise our rationale regarding this feature as best as I remember and can find from the BepInEx Discord server. I hope that this might also prompt some new discussions on the issue at hand since last talks lead to no changes.

To preface: all feature requests are always by default regarding upcoming new BepInEx versions. As such, this discussion will be related to BepInEx 6 development as BepInEx 5 is in Long Term Support mode and thus will not receive major changes to its API.

***

Just like with any plugin loader, plugin metadata is important as it allows plugin loaders to discern miscellaneous assemblies and classes from those that are of interest. On the other hand, metadata allows to subdivide code into reasonable chunks and tell the loader useful info about how to load the plugin. In case of BepInEx, plugin metadata is

* What classes should be considered as a loadable plugin
* Unique but readable plugin ID using [reverse domain notation](https://eqdn.tech/reverse-domain-notation/)
* Human-readable plugin name
* Plugin version as valid [semver 2.0](https://semver.org/) version
* Other plugins that the plugin depends on (as plugin ID + [npm semver range](https://docs.npmjs.com/cli/v6/using-npm/semver#ranges))
* Processes that the plugin should be loaded on (so-called process filters)

An important part of this is that this metadata exists for a plugin class. Just like you can have multiple classes in an assembly, you can thus also have multiple plugin classes in the same assembly. This has been used some cases alongside process filters so that you can load only specific plugins for each process but still ship them in the same DLL.

Moving metadata from classes to assembly has thus its own problems. Most notable of those are:

1. Different plugin classes require different metadata
    Oftentimes each `BepInPlugin` of a class is unique: each plugin has its own name, ID and version. In fact, each plugin class **must** have a unique ID. Thus if you have an assembly like

    ```cs
    // Which plugin does this GUID belong to???
    // In addtion, this is not a valid plugin ID!
    [assembly:Guid("a4df9f47-b2d9-49a9-b237-09220857c051")]

    [BepInPlugin(/*...*/)]
    class Plugin1 : BasePlugin { /* ... */ }
    
    [BepInPlugin(/*...*/)]
    class Plugin1Variation : BasePlugin { /* ... */ }
    ```
    Same applies for example to plugin dependencies and process filters.
   
2. What metadata is reasonable to move to assembly level?
    Related to the previous one, the question is: what metadata can and should be moved to assembly level?
    Is it just the human-readable name? Is it just the version? Should dependencies also be specified that way?

3. How the assembly-level data should be mapped to plugin-level?
    For example, normal .NET assembly versioning does not follow semver format which means that reading plugin version from default .NET attributes. 

    What if both plugin-level metadata and assembly-level meatadata is missing (e.g. you don't specify version in neither `BepInPlugin` or assembly attribute)? Right now `BepInPlugin` enforces you to specify the metadata which allows proper handling of it. That way there is a less chance of having plugin with version `0.0.0.0`.

    Does this need a custom attribute? If so, it adds API surface and has potential of confusion. Ability to do thing only one way in BepInEx allows for less confusion.

These are the ones I remember from our initial discussions. @bbepis and @ManlyMarco could add in their own opition on the topic since I might misremember something.

While there is #154, we haven't merged it as we still are still not in an agreement on this. As such, I hope for more discussion on this topic for solid solutions on raised issues.

**Comment by Measurity** [comment]
**Short answer:** 
Have an API similar to Harmony where you specify *how* the plugins are discovered. Either by requesting search of assembly X or specifying plugin types X, Y and Z.

**Long answer:**
I propose an API to define how the assembly should be loaded which should be internally used by BepInEx to load plugin meta data from attributes as well. Pseudo code:

```cs
BepInExLoader
    .WithPlugin(typeof(MyType), new PluginMetaData(NAME, VERSION, GUID))
    .WithPlugin(typeof(MyOtherType)) // Will use attribute or error out if not defined.
    .WithPlugin(typeof(MainPlugin), PluginMetaData.FromExecutingAssembly())
    .WithAssembly(Assembly.LoadFrom(...)) // Loads all BaseUnityPlugin/BasePlugin types for you, requires attributes on plugins to work.
    .Execute();
```

To get the same functionality as now you would use it like this:
```cs
BepInExLoader.WithAssembly(Assembly.GetExecutingAssembly()).Execute();
```

**Answering your points:**

> What classes should be considered as a loadable plugin

See pseudo code.

> Unique but readable plugin ID using reverse domain notation

I don't know why this is important. To me it seems redundant information because you have author + mod name. The purpose of an ID is to be unique, it doesn't have to be understandable.

> Human-readable plugin name

Could be provided by meta data or (as a fallback) inferred from output assembly name.

> Plugin version as valid semver 2.0 version

Can be done in AssemblyInfo.cs as well.
See: <https://kimsereyblog.blogspot.com/2018/04/sementic-versioning-for-dotnet.html>
`[assembly: AssemblyInformationalVersion("2.0.0+24.Branch.master.Sha.6e4b39ab28bb63227d9c418a9460fe344c0bacb2")]`

> Other plugins that the plugin depends on (as plugin ID + npm semver range)

Dependants can use unique GUID (with comment of which mod it is). Imposing readability on GUID has maintainability cons as mention in this ticket.

> Processes that the plugin should be loaded on (so-called process filters)
Does not conflict with current suggestion.

> What if both plugin-level metadata and assembly-level meatadata is missing (e.g. you don't specify version in neither BepInPlugin or assembly attribute)? Right now BepInPlugin enforces you to specify the metadata which allows proper handling of it. That way there is a less chance of having plugin with version 0.0.0.0.

Could be enforced if necessary. Definitely should decide but it's an easily solved problem.
