### ISSUE TITLE
BepInEx simply will not launch anymore in Valheim

### ISSUE THREAD

**Issue by cherbert** [BepInEx/BepInEx#193]
BepInEx simply will not launch anymore.

Game: Valheim

It was running perfectly for a week and now the console window doesn't appear anymore and the game loads without hooking BepInEx. I know it isn't because I've re-installed pretty much everything and the config files don't get created inside core.

I have moved the game folder, uninstalled the game completely deleted my saves folder, deleting everything. I have rebooted Steam, rebooted Windows and it still simply ignores BepInEx. I have it properly installed inside the game folder with the winhttp.dll etc.. 

I have tried the last 4 or 5 versions of BepInEx. I am running 64bit Windows and installing the 64bit BepInEx files.

I note a similar issue in the closed issues section but the person said a PC reboot fixed it. Mine isn't fixing on reboot. 

Any suggestions? You mention something about Steam Environmental Variables and a possible known issue? Anything I can do to give you more information I'll gladly do it.

**Comment by cherbert** [comment]
I managed to finally getting working by downloading the stripped files and putting them in managed. I am a bit confused though why it was working and then having re-installed the game it stopped working. I can only assume at some point a recent Valheim update the devs decided to strip out these DLL's.

**Comment by ghorsington** [comment]
Greetings!

From what I understand, you tried to use base BepInEx without using unstripped DLLs. Like mentioned in #182 and NeighTools/UnityDoorstop#10, Valheim needs unstripped DLLs.

I instead suggest using [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) since it is preconfigured and comes with the required unstripped DLLs without the need to overwrite any game files.

**Comment by ghorsington** [comment]
Closing this issue as I assume this got sorted out.

If you have any new problems, feel free to create a new issue ticket.
