### ISSUE TITLE
Console window Title

### ISSUE THREAD

**Issue by Sim-ian** [BepInEx/BepInEx#194]
**Is your feature request related to a problem? Please describe.**
Hosting multiple Valheim servers on the same hardware, it's impossible to see which console belongs to which server once running. 

**Describe the solution you'd like**
Could you please add the server name to the title of the console window, i.e. BepInEx 5.4.7.0 - Valheim **Sever Name**

**Describe alternatives you've considered**
I have tried using the Title command in the batch file that runs the servers to add the server name to the title bar but BepInEx overwrites it almost immediately in the start-up process.

**Additional context**
It would be most helpful if you could see the server name in the title area of the window so when doing maintenance on servers you can shut down the correct server and not have to randomly close servers.

**Comment by ghorsington** [comment]
This is now implemented as a separate plugin since it's game-specific: [Valheim.DisplayBepInExInfo](https://github.com/Valheim-Modding/Valheim.DisplayBepInExInfo)

This plugin is included by default in [BepInExPack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) which I suggest you to use.

Closing this issue as it has been solved by a plugin. If you have any BepInEx-related issues, feel free to create a new issue.
