### ISSUE TITLE
Plugins not loading

### ISSUE THREAD

**Issue by DJMrTV** [BepInEx/BepInEx#201]
**Describe the bug**
BepInEx wont load and plugins allthough there are plugins in the BepInEx/plugins folder

**To Reproduce**
It was like this from the beginning.

**Expected behavior**
It shold load the plugins i put in the plugin folder.

**Screenshots and logs**
```
[Message: Preloader] BepInEx 6.0.0-be.350 - Phasmophobia
[Message: Preloader] BLEEDING EDGE Build #350 from 07a69cf99b29f123f480ef26eaffe63a6879aa46 at master
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2019.4.7.15307441
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
```

**Desktop (please complete the following information):**
 Phasmophobia 0.26.8.1
 Bleeding Edge IL2CPP Artifact 350

**Additional context**
I tried using plugins from others and even tried making a plugin myself but it still wouldnt load the plugins i put in the plugin folder

**Comment by ghorsington** [comment]
Greetings!

Could you send over one example plugin so that I take a look at it?

Moreover, the log looks like it's from build 345 and not 350? Are you sure you are indeed using build 350? Could you remove the log you had, run the game again and send a new log that gets generated?

**Comment by DJMrTV** [comment]
I updated the log an example plugin that doesent work is RuntimeUnityEditor.

**Comment by ghorsington** [comment]
Thank you for the updated log!

Looking at the logs, everything works correctly. BepInEx 6.0 is currently not compatible with BepInEx 5 plugins which is why using something like RuntimeUnityEditor will not work. Instead you should use and write BepInEx 6 plugins.

In case of RuntimeUnityEditor, I suggest using [UnityExplorer](https://github.com/sinai-dev/UnityExplorer) which has builds for BepInEx 6.

**Comment by DJMrTV** [comment]
Thanks. Is there by any chance any documentation for BepInEx 6?

**Comment by ghorsington** [comment]
At this moment it's pretty scarce unfortunately since it is still in development. 

Right now I can only provide some starter examples to look at:

* [Basic example plugin](https://cdn.discordapp.com/attachments/754333645199900723/757320874553638984/BepInEx_IL2CPP_Example_Plugin.7z)
*  [Proper plugin written for BepInEx 6](https://github.com/wh0am15533/Il2CppCSharp-Trainer)

You can also try and join our [Discord server](https://discord.gg/MpFEDAg) and ask if someone has a ready example for a BepInEx 6 plugin.

There is a proper plugin template in the works but I am not sure when it will be done.

**Comment by DJMrTV** [comment]
Thanks for the help.
