### ISSUE TITLE
Linux server doesn't start with error line 67: file: command not found Cannot identify executable type (got )

### ISSUE THREAD

**Issue by alexandergolyakevich** [BepInEx/BepInEx#202]
**Describe the bug**

The server doesn't start with an error 
```
start_server_bepinex.sh: line 67: file: command not found
Cannot identify executable type (got )!
```
**To Reproduce**

1. I have a Linux server on VM on the cloud.google install server by the following instruction https://gameplay.tips/guides/9765-valheim.html
2. I try to run a server with the following instruction https://github.com/valheimPlus/ValheimPlus for server Unix use for it command "bashstart_server_bepinex.sh" 

Actual result: Server doesn't start with error 
```
start_server_bepinex.sh: line 67: file: command not found
Cannot identify executable type (got )!
```

**Expected behavior**

Server starts with mods Valheim plus

**Screenshots and logs**

<img width="1426" alt="Screen Shot 2021-03-07 at 22 05 47" src="https://user-images.githubusercontent.com/32876994/110251502-c3639180-7f91-11eb-9e58-ca77a7fd7f77.png">

**Desktop (please complete the following information):**
 - Game and game version [ Valheim 0.147.3]: 
 - BepInEx version [5.4.8]: 

**Additional context**

**Comment by ghorsington** [comment]
Greetings!

ValheimPlus uses its own pack of BepInEx and launch script which we do not manage. As such, you are better off filing an issue there instead of here since we didn't write their server launch scripts. As such, I'll be closing this issue and urge you to file it there.

That being said, the error clearly states that your Linux install is missing `file` command. If you are using Debian or Ubuntu, you can install it with

```
sudo apt update && sudo apt upgrade
sudo apt install file
```

You can first try installing `file` and trying again before filing an issue on [ValheimPlus GitHub issue tracker](https://github.com/valheimPlus/ValheimPlus/issues). From the looks of it, ValheimPlus supports LGSM which you might want to try using if working with Linux is not your cup of tea.

The only Valheim-specific BepInEx package that we manage is [BepInExPack for Valheim on Thunderstore](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/). If you have issues regarding the official BepInExPack and not ValheimPlus, feel free to create a new issue ticket here.

**Comment by alexandergolyakevich** [comment]
Thanks for your help, I solved the problems.
