### ISSUE TITLE
Failed to send data k_EResultLimitExceeded

### ISSUE THREAD

**Issue by Palindine** [BepInEx/BepInEx#217]
**Describe the bug**
BepInEx is flooding the server log with "Failed to send data k_EResultLimitExceeded" which results in getting disconnected from my connected server

**To Reproduce**

Started up game playing on my friends hosted server. Minutes within connection, in the process of building no less, the game would disconnect me. exited out stripped all mods off and ran with just BepInEx, getting same result. Game server  advance time but didnt save any build progress, but saved inventory

**Expected behavior**

I expected to be able to play the game without getting disconnected after a minute or two of playing on a server

**Screenshots and logs**

See https://pastebin.com/0ynRQ38Z for LogOutput.log

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Valheim 0.147.3
 - BepInEx version [e.g. 4.0]: 5.4.800 

**Additional context**

Unsure when problem first arose, noticed that the server did not save my 10 minutes from the other day. Problem does NOT exist when playing solo offline

**Comment by ghorsington** [comment]
Greetings!

Thank you for the logs. This error is specific to Valheim and how it configures networking, see for example the following post:

[Dedicated Server Error: k_EResultLimitExceeded](https://www.reddit.com/r/valheim/comments/lsroj0/dedicated_server_error_k_eresultlimitexceeded/)

The latest comments are from a day ago which implies the issue still persists in the game itself.

BepInEx is a general purpose modding framework and thus we cannot unfortunately help with game-specific issues. I suggest talking about it the game's own forums. If you have issues with plugins, there is [Valheim Modding Discord](https://discord.gg/RBq2mzeu4z) that has people who know about Valheim modding.

Since this issue does not appear to be directly related to BepInEx, I'm going to close it. If you do have any other issues, feel free to create a new ticket. You can still comment, however I am likely unable to help any further unless it directly relates to BepInEx.

**Comment by Windows10CE** [comment]
Could you try using https://valheim.thunderstore.io/package/Valdream/Data_Rate_Modifier/ on your server? As far as I know the game caps all network activity to 50kbps, including on dedicated servers, which according to my (admittedly a bit brief) search in the Valheim Discord has caused problems before
