### ISSUE TITLE
Errors in solution

### ISSUE THREAD

**Issue by PhilPJL** [BepInEx/BepInEx#221]
**Describe the bug**
Sorry if these are 'noob' errors, but just opened BepInEx from main branch and received a few errors

**To Reproduce**
Open main branch using VS 2019

1) Asked to fix incorrect configuration mappings
Two projects are configured as Release for the Debug configuration - is this by design?
![image](https://user-images.githubusercontent.com/271656/113576518-9c8f8e00-9617-11eb-8048-a44a011aa7ca.png)
Changing these to debug fixed the error.

2) Missing reference in BepInExTests
![image](https://user-images.githubusercontent.com/271656/113578087-2f312c80-961a-11eb-8af7-0fc0433d2071.png)
![image](https://user-images.githubusercontent.com/271656/113578716-268d2600-961b-11eb-9e5d-f4a799231335.png)
![image](https://user-images.githubusercontent.com/271656/113578853-60f6c300-961b-11eb-901b-679ba5dfc0aa.png)

Also warning on UnityEngine, because the Nuget package only specifies .NET 3.5 and this is a .NET Core 3.1 project.
Presumably you don't need an assembly ref here because you get the UnityEngine ref transitively.

3) Compatibility warning
![image](https://user-images.githubusercontent.com/271656/113577829-cc3f9580-9619-11eb-88ab-9080a82a7a8a.png)
![image](https://user-images.githubusercontent.com/271656/113578739-2f7df780-961b-11eb-975e-a98340b299f8.png)
You may need to make BepInExTests target .NET 5 and add UnityEngine.InputLegacyModule to UnityEngine.Core?

Where is the source for UnityEngine.Core?  I don't see it in this repo.
Spelling mistake: 
![image](https://user-images.githubusercontent.com/271656/113584264-97840c00-9622-11eb-9b27-cf32cbe8bfcc.png)

**Comment by ghorsington** [comment]
Greetings!

Thanks for the input. Here are some comments on this

> Two projects are configured as Release for the Debug configuration - is this by design?

Appears to be a misconfiguration from long ago. Going to fix it in a bit.

> Missing reference in BepInExTests

Looks like a missing ref from when we moved UnityEngine files to NuGet. Going to fix it in a bit.

> Presumably you don't need an assembly ref here because you get the UnityEngine ref transitively.

Unfortunately you do since UnityEngine.Core is marked as a development dependency.

> You may need to make BepInExTests target .NET 5 and add UnityEngine.InputLegacyModule to UnityEngine.Core?

Going to fix it by moving target to `net5`. You don't need `UnityEngine.InputLegacyModule` as relevant classes are already part of UnityEngine.dll.

> Where is the source for UnityEngine.Core? I don't see it in this repo.

There is none since it's simply stripped UnityEngine.dll taken from Unity 5.6. Going to add net5 target so that tests won't complain about it.

I'll close the issue once I have pushed the fixes.

**Comment by PhilPJL** [comment]
@ghorsington All fixed except I now get
![image](https://user-images.githubusercontent.com/271656/113600120-7548b900-9637-11eb-80f1-5ee39ead2ba6.png)
not sure how to fix that.

**Comment by ghorsington** [comment]
This is because BepInEx.Unity targets only net35. This is how it is supposed to be; there is no simple proper fix for that at the moment. [I added a comment about it into cspro](https://github.com/BepInEx/BepInEx/blob/master/BepInExTests/BepInExTests.csproj#L34) until we decide whether we need tests and how we would use them.

**Comment by PhilPJL** [comment]
Ok.  

You have this also

![image](https://user-images.githubusercontent.com/271656/113600958-a70e4f80-9638-11eb-86a0-87e3e8c182c9.png)

which seems to be fixable by deleting the Mono.Cecil assembly ref.

**Comment by ghorsington** [comment]
Appears to be a remnant back from when we moved to new csproj format; removed that now

**Comment by PhilPJL** [comment]
@ghorsington ok so last thing honest :)  Why are there a load of 'naming rule violation' warnings that don't appear to make sense?

![image](https://user-images.githubusercontent.com/271656/113602162-31a37e80-963a-11eb-9bd1-2b0aea102907.png)
![image](https://user-images.githubusercontent.com/271656/113602288-5861b500-963a-11eb-920f-7b6781aaaea9.png)

Is your editor.config screwy or do you have an unusual naming convention?
