### ISSUE TITLE
IL2CPP Preloader - fatal error when getting unity version info

### ISSUE THREAD

**Issue by BlacRyu** [BepInEx/BepInEx#229]
**Describe the bug**
I'm getting a fatal error in the preloader when launching the game SaGa Frontier Remastered with BepInEx. It seems there is some extra information being passed through when it tries to access the file version info from the .NET API.

**Screenshots and logs**
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/6328008/LogOutput.log)
![image](https://user-images.githubusercontent.com/10762433/115087275-b73cef00-9ec2-11eb-9c3a-8202a416d99e.png)
In this screenshot I used a custom build to print the full file version info. You can see extra data gets added to all the file version info string properties.

**Desktop (please complete the following information):**
 - Game and game version: SaGa Frontier Remastered v1.0 (Steam build [6443908](https://steamdb.info/patchnotes/6443908/))
 - BepInEx version: 6.0.0 x64 Bleeding Edge 361

**Comment by Kein** [comment]
This can be addressed with basic string version slice to 10-11 chars, since for Version Parse you only need  major, minor and build, however, this raises the question what would you do if version is stripped? You can fallback to UnityPlayer module version lookup, but what if it is stripped from there too? 

I think as a final failure it worth to expose config string where user can specify custom version and instead catch exception in version parsing and print the info about config option.
