### ISSUE TITLE
ChainLoader.HasBepinPlugins returns false when inheriting from class from another Assembly.

### ISSUE THREAD

**Issue by xoxfaby** [BepInEx/BepInEx#240]
**Describe the bug**
ChainLoader.HasBepinPlugins, more specifically [Line \#253](https://github.com/BepInEx/BepInEx/blob/61bc72861e81ba2e70222b8f9a08992fc7b5b8d5/BepInEx/Bootstrap/Chainloader.cs#L253) checks if the Assembly references BaseUnityPlugin.
```cs
if (ass.MainModule.GetTypeReferences().All(r => r.FullName != typeof(BaseUnityPlugin).FullName))
	return false;
```
The problem occurs if one inherits from a class with BaseUnityPlugin as the base class while not directly referencing BaseUnityPlugin in the assembly. This works perfectly fine, but the above line of code rejects the assembly for not having a TypeReference to BaseUnityPlugin. This can easily be worked around by including any reference to the type BaseUnityClass in the assembly, but it shouldn't be necessary. 

**To Reproduce**
Assembly1.dll
```cs
class CustomUnityPlugin : BaseUnityPlugin { } 
```

Assembly2.dll
```cs
class ExtraCustomUnityPlugin : CustomUnityPlugin { } 
```

Bepinex will not load Assembly2.dll even though the plugin works perfectly fine, which can even be demonstrated by including a dummy reference to BaseUnityPlugin like
```cs
class ExtraCustomUnityPlugin : BaseUnityPlugin 
{
    private BaseUnityPlugin pointless;
} 
```
which makes the plugin load fine. 

**Expected behavior**
Any assembly that contains a subclass of BaseUnityPlugin should get loaded. 

**Screenshots and logs**
n/a

**Desktop (please complete the following information):**
 - BepInEx version [e.g. 4.0]:  5.4.9

**Comment by ghorsington** [comment]
Greetings!

This is indeed a problem. Initially, the line was added for performance purposes: if there wasn't any reference to BaseUnityPlugin, the assembly could be assumed not to have any loadable plugins at all. BepInEx uses Cecil to discover loadable assemblies in order to prevent mass loading of DLLs.

I'll fix this by changing the reference requirement from `BaseUnityPlugin` to `BepInPlugin` attribute type. This should be more fitting as every loadable plugin must have that metadata attribute set. Moreover, the attribute itself wasn't designed to be inheritable which makes it a better tool to detect loadable BepInEx plugins.

I will close the issue once the fix is applied.
