### ISSUE TITLE
Valheim will not launch with BepInEx active 

### ISSUE THREAD

**Issue by BobDonner** [BepInEx/BepInEx#248]
Valheim was updated on 5/12/2021. When I tried to launch the game everything proceeded normally until the Valheim startup screenup appeared and then a small text box popped onscreen. The box was labeled "Valheim - Unity 2019.424f1_5da6f0345e82".

[https://www.mediafire.com/view/1x9emiuugtoxytg/error_message.jpg/file](url)
I removed all mods from the BepInEx/plugins folder and the same problem occurred.

Anyone who has an updated version of Valheim is probably experiencing the same issue. When I disable BepInEx by renaming the main BepInEx folder the game launches properly. 

Valheim 0.153.2
BepInEx 5.4.11

**Comment by Windows10CE** [comment]
Could you try using the release of BepInEx from here? https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

**Comment by CreepyGnome** [comment]
The version number listed on that site is the same as on NexusMod and the one I have that also has this issue and is aligned with latest on NexusMod. Since I never heard of "thunderstore.io" I am not going to download from them to test, if there has been an update can NexusMod get the update please.

**Comment by Windows10CE** [comment]
The Thunderstore release contains unstripped DLLs specific to Valheim that the GitHub release does not. Any release that you get from Nexus/Vortex also need to have these DLLs in them, as they're required for BepInEx to function correctly. Also, none of the BepInEx maintainers have access to the versions of BepInEx hosted by Nexus, nor any of the mods on Nexus that ship with BepInEx. If those copies need to be updated, please contact the maintainers of those packages to tell them that.

The Valheim update did not require an update to BepInEx itself, just to the unstripped libraries that are also shipped with it. That's why the version numbers are the same, other than Thunderstore having an extra `01` at the end.

**Comment by ghorsington** [comment]
Greetings!

This looks like a duplicate if #246.

We do not manage releases on NexusMods nor Vortex -- you'll have to contact those people who do it. The only Valheim-specific distribution that we have and officially manage is the one on Thunderstore.

I'm closing the issue since this looks like a duplicate. If you do indeed have something that is not related to #246, feel free to create a new ticket using the proper issue template and fill out all the information we usually need to help.

**Comment by BobDonner** [comment]
Hello Geoffrey,
My most profound apologies for not searching for a similar problem before I
opened a new ticket. I am so sorry to have wasted your time.

I downloaded the file from the link supplied and now my game works
perfectly with all of the mods that I use running just finel

Thanks to you and all of the others in the modding community that make it
possible for mods to work as it lets us play games the way that we want
rather than being restricted to playing the way that the devs wanted us to.

respectfully yours,
Scptt  (Bob Donner)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
