### ISSUE TITLE
Game won't launch with latest version of BepInEx

### ISSUE THREAD

**Issue by AlexandruVerenca** [BepInEx/BepInEx#250]
I am using the latest version of BepInEx from the thunderstore mod manager (5.4.1001). I've tried reinstalling BepInEx & disabling all other mods so far and nothing changed. Game will only launch without BepInEx.
![Screenshot 2021-05-13 123035](https://user-images.githubusercontent.com/16123232/118107240-2f75d200-b3e7-11eb-9288-4a7b93580b8c.png)

**Comment by ghorsington** [comment]
Greetings!

If you did indeed properly install the latest version of [BepInExPack Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/), it should work fine. I personally am unable to reproduce your issue with the latest Valheim version and BepInExPack for Valheim installed.

Since you are using Thunderstore Mod Manager, I suggest creating a fresh user profile on which you first only install BepInEx.

You can also check that you indeed have the latest unstripped Unity libraries. For that, go into your game folder and check that you have a folder named `unstripped_corlib`:

![image](https://user-images.githubusercontent.com/13762037/118109106-6c42c880-b3e9-11eb-953e-4cdb81261db3.png)

Check the folder's size. The size of this folder that is shipped with the latest version of BepInEx is `15 869 440 bytes`:

![image](https://user-images.githubusercontent.com/13762037/118109205-8ed4e180-b3e9-11eb-8ead-866ac30c20e4.png)

While the old folder's size is lower, at `15 861 760 bytes`. If you still have the older folder even after you have updated to 5.4.1001, you should perhaps contact Thunderstore Mod Manager developers and seek assistance.

**Comment by AlexandruVerenca** [comment]
You are correct about the folder size, I still have the older folder it seems.

**Comment by ghorsington** [comment]
As a quick fix you can download latest BepInExPack off Thunderstore manually and just replace your unstripped_corlib with the one in the zip file. Though I'd probably try and properly investigate why yours didn't update automatically.

**Comment by AlexandruVerenca** [comment]
Thank you, downloading manually worked!
