### ISSUE TITLE
Slow Fps and menu option slow down

### ISSUE THREAD

**Issue by ShaneFreak** [BepInEx/BepInEx#252]
**Describe the bug**

**To Reproduce**
BepInEx 5.4.11, BepInPluggin 16.3, lastest graphic dll and BepInEx configuration toolbar was installed.

**Expected behavior**
Completely newly extracted game with these plugins result in slow fps even when there is plenty of video ram left to utilize.

**Screenshots and logs**

**Desktop (please complete the following information):**
 - Honey Select 2 (better repack R5)
 - BepInEx 5.4.11
 - 

**Additional context**
This problem is coming when ever I load BepInEx 5.4.4 or above.

**Comment by ghorsington** [comment]
Greetings!

Could you please elaborate? It is great that you did use the proper issue template. However, you left out a lot of *crucial* information. Most importantly, what game are you using BepInEx on?

FPS issues are not simple to debug since different plugins can affect game performance differently. I suggest testing if there are specific plugins that you use that cause issues.

**Comment by ShaneFreak** [comment]
I have edited it, please review.

**Comment by ghorsington** [comment]
This issue is somewhat similar to #280 as the poster also reported FPS drops in the game. Reinstalling BepInEx and plugins from scratch helped him as he had a lot of old plugins.
You can review the issue ticket and try using the BepInEx build I gave him.

Even better, I suggest (re)installing [HF Patch](https://github.com/ManlyMarco/HS2-HF_Patch/releases) and enable options that clean your game directory.

As the issue is stale and likely fixed by #280, I'll close this ticket. If you have any further problems, feel free to create a new ticket.
