### ISSUE TITLE
No damage to trees or small rocks

### ISSUE THREAD

**Issue by DannyEss** [BepInEx/BepInEx#253]
**Describe the bug**
I can't make any damage to Trees or rocks on my Valheim dedivated server. I'm playing the game with my friend and she's got the same issue. It works either Online on our dedicated server or on a local server

**To Reproduce**
I just try to cut a tree or farm any rocks

**Expected behavior**
If you cut a tree, the tree should go to an fall animation and after cutting it again, it should disappear and leave a pile of wood. 

**Screenshots and logs**
```
[Error  : Unity Log] MissingMethodException: string ZNetView.GetPrefabName(UnityEngine.GameObject)
Stack trace:
(wrapper dynamic-method) DropTable.DMD<DropTable::GetDropList>(DropTable)
(wrapper dynamic-method) DropOnDestroyed.DMD<DropOnDestroyed::OnDestroyed>(DropOnDestroyed)
(wrapper dynamic-method) Destructible.DMD<Destructible::Destroy>(Destructible)
Destructible.RPC_Damage (System.Int64 sender, HitData hit) (at <fda64833b4b74020987bc5f624178286>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Delegate.DynamicInvoke (System.Object[] args) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <fda64833b4b74020987bc5f624178286>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <fda64833b4b74020987bc5f624178286>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <fda64833b4b74020987bc5f624178286>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <fda64833b4b74020987bc5f624178286>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <fda64833b4b74020987bc5f624178286>:0)
(wrapper dynamic-method) Destructible.DMD<Destructible::Damage>(Destructible,HitData)
Attack.DoMeleeAttack () (at <fda64833b4b74020987bc5f624178286>:0)
Attack.OnAttackTrigger () (at <fda64833b4b74020987bc5f624178286>:0)
Humanoid.OnAttackTrigger () (at <fda64833b4b74020987bc5f624178286>:0)
CharacterAnimEvent.OnAttackTrigger () (at <fda64833b4b74020987bc5f624178286>:0)
```
**Desktop (please complete the following information):**
 - Game and game version 0.153.2
 - BepInEx version 5.4.10.0
 - Valheim Plus 0.9.7

**Additional context**

**Comment by ghorsington** [comment]
Greetings!

Thank you for the log and the report! Judging by the log, you have some mods installed which appear to be outdated. You mentioned Valheim Plus which could cause issues. However, it is hard to tell since you did not include the entire log.
Nevertheless, it is clear that some mod causes issues because of `DMD`s which are in this case patched versions of original methods. BepInEx itself is a general Unity modding framework and does not apply any game-specific patches like what is happening here.

I suggest finding out what plugins you have installed and checking which one causes the problem. Moreover, I urge you to seek help from Valheim modding community since this repository is for a game-agnostic modding tool. One place to check out is the [Valheim Modding Discord](https://discord.gg/RBq2mzeu4z). Moreover, Valheim Plus has its own GitHub repo at [valheimPlus/ValheimPlus](https://github.com/valheimPlus/ValheimPlus).

I am closing this issue as it is nothing we can fix on our side. If you have any other issues, feel free to create a new issue ticket.

**Comment by DannyEss** [comment]
Thanks a lot, I'll disable all Plugins one by one to see which one causes the trouble. I saw, that there is a Valheim Plus update since yesterday, which could cause the trouble
