### ISSUE TITLE
Cannot run run_bepinex.sh

### ISSUE THREAD

**Issue by petteyg** [BepInEx/BepInEx#260]
Trying to run BepInEx_unix_5.4.11.0.zip with Dyson Sphere Project.

Extracted, edited the single line in the script to DSPGAME.exe and game launch options, and get

`Cannot identify executable type (got Bourne-Again shell script, ASCII text executable)!`

**Comment by petteyg** [comment]
Adding |*x86-64* to the case does not seem to work for some reason, though the output from `file` contains the string. Manaually setting arch=x64 works. Now I run into
`/usr/bin/env: symbol lookup error: /home/petteyg/.steam/steam/steamapps/common/Dyson Sphere Program/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen`

**Comment by petteyg** [comment]
I modified run_bepinex.sh some more,

```
export LD_LIBRARY_PATH="${doorstop_libs}":/usr/lib64:${LD_LIBRARY_PATH}
export LD_PRELOAD=$doorstop_libname:libbfd.so:$LD_PRELOAD
```

Got a little farther, now:

`/home/petteyg/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point: line 95: Failed: command not found`

**Comment by Windows10CE** [comment]
Which BepInEx to download depends on what platform the game is compiled for, not the platform it's being run on. Since DSP doesn't have a Linux release, you need to use the Windows version of BepInEx and run the game through proton or wine.
Getting the Windows BepInEx to work on Linux requires a change to the wine prefix you run the game in. You can find instructions for how to do that for a proton game over at https://github.com/risk-of-thunder/R2Wiki/wiki/Getting-BepInEx-Console-Working-on-Linux#legacy .
