### ISSUE TITLE
Harmonyx error

### ISSUE THREAD

**Issue by m1371339094** [BepInEx/BepInEx#285]
[Error  :  HarmonyX] Failed to process patch System.Void HS2_RandomHPicker.Hooks.STRConfirmation_SetPlayerDontSelect_CreateRandomButtons(HS2.STRConfirmation) - Could not find method SetPlayerDontSelect with NULL parameters in type HS2.STRConfirmation

**Comment by ManlyMarco** [comment]
Check in dnspy if this method actually exists in game assembly.

**Comment by ghorsington** [comment]
Greetings!

How are you annotating your patch? As the error mentions, Harmony cannot find a method in `HS2.STRConfirmation` type with signature `SetPlayerDontSelect()` (that is, no parameters). What's the full signature of the method you're trying to patch?
Note that the signature may have changed between, for example, game updates. This means that you might need to update the patch.

**Comment by m1371339094** [comment]
how do i find the update patch?

**Comment by m1371339094** [comment]
I also have the problem Can't remove RectTransform because LayoutElement (Script) depends on it

**Comment by ghorsington** [comment]
The patch is found in the plugin. Are you the developer of the plugin or are you just using the plugin?

**Comment by m1371339094** [comment]
using it

**Comment by m1371339094** [comment]
[Plugins.zip](https://github.com/BepInEx/BepInEx/files/6910020/Plugins.zip)

**Comment by ghorsington** [comment]
> using it

In that case, you should contact the author of the plugin about the problem or check if there is a new version of it. This repository is for the general BepInEx framework and we, unfortunately, can't provide support for specific plugins.   
If you don't need the `RandomHPicker` plugin, you can remove its DLL from `plugins` folder which should get rid of the original error.

The patching error you're getting is either because the plugin is out of date or your game is not updated. I suggest seeking help in a game-specific community. Judging by the `HS2` prefix in the plugin, you're likely modding Honey Select 2. For that game, there is [IllusionSoft Discord](https://discord.gg/illusionsoft) server in which you can ask for help related to that game. There can be some other communities as well, but whichever they are, you're likely to get better help to your outdated plugin there than here.

As such, I'll be closing the issue as there is not much we can do on our side. If you have further issues, feel free to create a new ticket, though.
