### ISSUE TITLE
[BepInEx v4.0] Problems

### ISSUE THREAD

**Issue by SiTWulf** [BepInEx/BepInEx#32]
The new version of BepInEx is not Compatible with [PatchWork](https://github.com/kkdevs/Patchwork).
If you run the PatchWork exe file, No load any plugin. Not problem at all with the BepInEx 0.3.2 version.

The new version of BepInEx is not Compatible with IPA plugins, the plugin IPA Plugin Loader 1.2 is loaded but not work any of IPA plugins.

**Comment by beitadoro** [comment]
I did a clean install from scratch and didn't get IPA Plugin work
In output_log.txt:
...
[Info] Loaded [IPA Plugin Loader 1.2]
...
TypeLoadException: Could not load type 'BepInEx.Chainloader' from assembly 'IPALoader'.

**Comment by denikson** [comment]
BepInEx 4.0 introduced some minor API changes that may affect Patchwork. We tried to keep compatibility as high as possible, but unfortunately some compromises had to be made.

Please contact the developer of Patchwork for the fix. You can use the issue tracker of Patchwork.  
Until then, please use the hardpatch version of Patchwork instead of the launcher.

As for IPA Loader, the fix is under way as well along with fixes for other BepisPlugins.

That all said, please post issues related to **BepInEx itself**. For issues related to IPA Loader there is [BepisPlugins](https://github.com/bbepis/BepisPlugins) that has an issue tracker as well.
