### ISSUE TITLE
BepInEx 4.0 / IPA 3.3 conflict ?

### ISSUE THREAD

**Issue by Owll99** [BepInEx/BepInEx#35]
**Describe the bug**

Error message when trying to launch Koikatu 3.0 if BepInEx 4.0 and IPA 3.3 are installed, no error message if one or the other is installed alone.

**To Reproduce**
A short description of what you did for the bug to happen.

Clean install of the game and then BepInEx and IPA.

**Expected behavior**

Game launch normally without error message and if mods are installed, It's working correctly.

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

[preloader_20180713_144122_892.log](https://github.com/BepInEx/BepInEx/files/2192669/preloader_20180713_144122_892.log)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: Koikatu 3.0
 - BepInEx version [e.g. 4.0]: BepInEx 4.0

**Additional context**

**Comment by bbepis** [comment]
BepInEx is not compatible with IPA. This was not very obvious with v3.2 and prior, but due to the new patching feature they conflict to the point of not being able to start.

BepInEx expects a clean `Managed` folder to be able to run the patching function (not exactly, there's circumstances where editing the managed folder is still okay, but generally not other programs that patch these files like IPA since the .DLLs get mangled).

For a more detailed explanation, IPA causes UnityEngine.dll to reference IllusionPatcher.dll (IPA .dll), and IllusionPatcher.dll references UnityEngine.dll, causing a circular dependency which prevents patching being able to work.

I don't believe there is a fix I can make for this, but even if there was I don't believe I would implement it since it may cause restrictions for patchers and/or more problems down the line. IPA and BepInEx are independent plugin frameworks, and should be treated as such.

However I have made a plugin that loads IPA plugins by emulating the APIs that IPA plugins need, as part of [BepisPlugins](https://github.com/bbepis/BepisPlugins) (IPALoader). It works for 99% of plugins (there's only a single plugin that I know of that doesn't work with it, since I took a shortcut with implementing the emulation; going the full mile and getting everything working requires at least triple the current code of the plugin so I decided against looking into it)
