### ISSUE TITLE
"Quick save" game option

### ISSUE THREAD

**Issue by necros2k7** [BepInEx/BepInEx#353]
### Describe your proposal

Is it possible to make such option even buggy even in same session without pc reboot?

### Proposed solution

Make Unity process dump and then reload it in RAM

### Alternatives

For example in 200x Save and load fuction was realized with
https://www.softportal.com/getsoft-2798-detectivestory-1.html

**Comment by ghorsington** [comment]
Greetings!

Thank you for the suggestion and sorry for the delayed reply. Unfortunately, this is out of the scope of core BepInEx. Instead, this can be done as a plugin for a game you want to mod.

Moreover, the trainer you linked seems to implement saving for different games instead of having a general solution (which is undoubtedly very difficult if not impossible). The same thing can be done by making a plugin for a game you want to mod. The suggestion is better suited to the particular modding community than core BepInEx.

I'll close the issue for now as it is out of scope for us.
