### ISSUE TITLE
Trying to run Linux run_bepinex.sh on a windows game's exe

### ISSUE THREAD

**Issue by hub2git** [BepInEx/BepInEx#435]
### What happened?

```
/run_bepinex.sh 
./run_bepinex.sh: 91: cd: can't cd to /home/me/.wine/drive_c/Games/Desperados 3/BepInEx//home/me/.wine/drive_c/Games/Desperados 3
/Desperados III.exe
Cannot identify executable type (got cannot open `/Desperados III.exe' (No such file or directory))!
Please create an issue at https://github.com/BepInEx/BepInEx/issues.

```

### Steps to reproduce

1. The game is the Windows version of Desperados 3. (I'm running the game through Lutris / Wine)
2. I got BepInEx 5.4.19 https://github.com/BepInEx/BepInEx/releases/download/v5.4.19/BepInEx_unix_5.4.19.0.zip.
3. I extracted the zip into a a bepinex folder nested inside the Desperados3 folder.
4. I edited Line 15 in run_bepinex.sh so that it now looks like this: `executable_name="/home/me/.wine/drive_c/Games/Desperados 3/Desperados III.exe"`
5. In /.wine/drive_c/Games/Desperados 3/BepInEx, I run`chmod u+x run_bepinex.sh`
6. I then run `./run_bepinex.sh`.

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
I don't have a LogOutput.log file.
```

### Environment

```markdown
- OS: Linux Mint 20.3
- BepInEx: 5.4.19
- Game:  Desperados 3
```

**Comment by ghorsington** [comment]
Greetings!

Because running games via wine means essentially running a Windows game, you need a *Windows version of BepInEx*. Additionally, you will need to configure wine to use native `winhttp.dll` before the built-in version. You can refer to the [proton/wine setup guide](https://docs.bepinex.dev/articles/advanced/steam_interop.html#protonwine) for more information, and adjust as needed for your specific wine setup.

**Comment by hub2git** [comment]
thank you for your quick reply. 
I got the Windows version of BepInEx. I extracted into the game's folder. 
I went to winecfg and added the winhttp.dll in the Library tab, as the linked guide instructs.
I ran the game and there is now a "LogOutput.log" file.
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/8989459/LogOutput.log)
.

I then exited the game and unpacked a mods zip file for desperados 3. i got the zip file at https://github.com/benediktwerner/Desperados3Mods.
I unpacked them into the /Desperados 3/BepInEx/plugins folder.

**Comment by ghorsington** [comment]
Based on the logs, BepInEx works now fine. As for the plugin, you likely downloaded the source code instead of the compiled plugin. I suggest following the proper installation guide in the repo's readme and asking the plugin developer instead.

Since the original issue is resolved, I'm marking the issue as completed. As for the plugin, please contact the plugin developer and refer to the plugin's own installation guide.

**Comment by hub2git** [comment]
I wasn't sure how to interpret the log, so thanks for letting me know that BepInEx works fine.
