### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Yarioos** [BepInEx/BepInEx#44]
BepInEx 4.0.0.0 - Koikatu
[Message] Preloader started
[Fatal] Could not run preloader!
[Fatal] System.MissingMethodException: Method not found: 'Mono.Cecil.AssemblyDefinition.Dispose'.
  at BepInEx.Bootstrap.Preloader.Main (System.String[] args) [0x00000] in <filename unknown>:0

i did what was asked

**Comment by denikson** [comment]
Greetings! Pardon the late response.

Before posting issues, please refer to the [contribution guide](https://github.com/BepInEx/BepInEx/blob/master/CONTRIBUTING.md#bug-reports) to create a more descriptive issue report.  

If reading is not your cup of tea, please use one of the **issue templates** that you only need to fill out. For instance, you can use the *Bug report* template for such error reports.

Everything considered, we cannot really provide proper help until you provide more information about the game, what plug-ins/tools you have installed and what you tried to do prior to the error appearing.

From the looks of it, you might have a wrong version of Mono.Cecil installed.  
Make sure you have only one `Mono.Cecil.dll` in your game folder (you can use Windows' search file search for that) and that it's located in `BepInEx/core` folder.

Then, reinstall the latest stable release of BepInEx, as it should contain the right version of Mono.Cecil.

I'm closing the issue for since it's lacking additional information. If you still have the problem, please reopen the issue using the "Bug report" template.

**Comment by Rbmukthegreat** [comment]
Hello ghorsington,

I was creating a mod with lethal company, and so had installed Mono.Cecil.dll and Mono.Utils into the games Managed folder. Like you said, when I tried to run BepInEx it would just not load the console, and I couldn't figure out what was going on. Thank you so much for leaving this comment, it really helped me.
