### ISSUE TITLE
Problems installing for Astronauts: Sirius game

### ISSUE THREAD

**Issue by adgjlp** [BepInEx/BepInEx#447]
### What happened?

BepInEx doesn't appear to install properly for the game Dungeon of Regalias because no config file/folder is generated when running the game. I'm using the x86 version for this 32-bit game. I was hoping to use Unity AutoTranslator to translate the game. Thank you for your time in helping me solve this issue.
![image](https://user-images.githubusercontent.com/81662907/179442381-46000040-5952-4ddb-82d7-f2e7328c79a4.png)

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
N/A
```

### Environment

```markdown
- OS: Windows 10
- BepInEx: 5.4.20
- Game: Dungeon of Regalias
```

**Comment by ghorsington** [comment]
Greetings!

Based on the screenshot you provided and info on the internet, the game does not use Unity (and doesn't seem to be .NET-based in the first place). BepInEx is intended only for Unity games and games that use .NET-based libraries like XNA or MonoGame. As such, you cannot use XUnity.AutoTranslator (I assume you mean that by "Unity AutoTranslator") with the game.

I'll close this issue as not actionable since the game does not appear to use any supported game engines.
