### ISSUE TITLE
Managed Dependencies, Managed & Plugin priorities, loading queue configuration

### ISSUE THREAD

**Issue by enkephalin07** [BepInEx/BepInEx#48]
Specify by assembly name where in the load order a plugin is best loaded. Egs:
[ManagedDependency("UnityEngine.dll")]
[ManagedDependency("Assembly-CSharp-firstpass.dll")]
so a plugin would only load after these are initialized.

Inversely, an attribute to identify which assemblies a plugin should come before. These would be superseded by dependency attributes and, naturally, BepInEx.

**Comment by denikson** [comment]
Greetings,

thank you for the feature request! I noticed you chose not to use the `Feature request` template that was specifically made for these kind of issue tickets. 
Thus, would you mind elaborating the rationale behind your idea?

The way BepInEx is currently set up requires most assemblies to being loaded into memory during preloader. What you ask would mean rewriting how the preloader functions or requiring preloader to be disabled altogether in order to use this feature. This is why I'd really like to hear your reasoning for such a request.

If you absolutely need to do some work before a game assembly gets loaded, you can already use preloader patcher finalizers for most of that work.

**Comment by enkephalin07** [comment]
I'll have to get back to this after taking a more complete look at the code. Thanks for replying.
