### ISSUE TITLE
Unable to run in wine

### ISSUE THREAD

**Issue by boinkey** [BepInEx/BepInEx#52]
BepInEx doesn't seem to load under wine (www.winehq.org).

I tried a game in wine. The game itself runs fine, but BepInEx doesn't seem to run. I tried verifying this by enabling the console, and it didn't show up. My guess is that the dll doesn't load for some reason, but I am not familiar with windows or mono, so I don't know how to debug it. One possibility is that another version of mono is being loaded, but I don't know which one or from where.

Game: insult Order 1.03
BepInEx 4.1 (I think, came with the game so it should be fine) 

cheers,
//B

**Comment by bbepis** [comment]
BepInEx makes use of [Doorstop](https://github.com/NeighTools/UnityDoorstop) to be able to load patchlessly. This takes advantage of how dynamic linking works in Windows (using the import table), and this probably works differently under Linux, which is why it's not working for you. (I'm not sure if Wine isn't implementing that import table correctly, or if they're using alternate behavior on purpose)

You should be able to go around this by manually patching the game, which doesn't invoke any windows-specific behaviour. I've kept the legacy patcher in the source code of BepInEx for something like this, so you should be able to build it yourself and run it.

As far as I know, you only need to install the `mono-complete` metapackage from the [Mono repository](https://www.mono-project.com/download/stable/#download-lin). You should be able to compile the solution with `msbuiild` and run the patcher with `mono`.

The patcher requires the other projects in the solution to be built first, so I wouldn't suggest building the project by itself. I don't believe you need to change the build platform as only the UnityDoorstop component is dependent on the platform type (x86 or x64).

After building it, the patcher needs to be run in the same current directory as the game .exe (Assuming that your managed folder is in the `(gamename)_Data/Managed` location. If not, you'll need to [modify the code yourself](https://github.com/BepInEx/BepInEx/blob/master/BepInEx.Patcher/Program.cs#L44) and change the location).

Let me know if you run into any more problems.

**Comment by softashell** [comment]
Doorstep loader works fine in wine, just have to use winecfg to change DLL override for winhttp to "Native then Builtin" to try loading dll from game directory first.

**Comment by denikson** [comment]
This looks like it's pretty much answered, so I'll keep my input short.

As @bbepis noted, Doorstop (and Sybaris if you play Custom Maid 3D games) are based on the vital fact that Windows' DLL search strategy causes the game to load Doorstop instead of real winhttp, which in turn allows it to do all the magic (which is not that magical at all; the source code is on github, just don't crucify me for it, since it was my first time writing low-level hooks).

The issue is indeed that by default wine has a different DLL loading strategy, preferring its own builtin DLLs to ones provided in the application folder. That makes sense to be honest.

> Doorstep loader works fine in wine, just have to use winecfg to change DLL override for winhttp to "Native then Builtin" to try loading dll from game directory first.

Nice, @softashell! Thank you! 
I didn't know wine allowed you to change the DLL search strategy. This is indeed good, thank you again! I'll update the wiki to add a note about it. 
We never really thought of the possibility of using Doorstop with wine, since we haven't encountered that many Linux users. Moreover, we have the static patcher which does the job.

**Comment by boinkey** [comment]
Ok, 

So here is what I did:

1. Clone BepInEx
git clone https://github.com/BepInEx/BepInEx.git

2. Install latest mono version according to (took care of C# 7 errors)
https://www.mono-project.com/download/stable/#download-lin
sudo apt-get install mono-complete

3. Install package needed to build BepInEx
cd BepInEx/
mkdir packages
cd BepInEx.Patcher
wget http://nuget.org/nuget.exe
mono nuget.exe restore  -PackagesDirectory .
mv BepInEx.Patcher/ILRepack.* packages/
mv BepInEx.Patcher/Mono.Cecil.0.10.0 packages/

4. Got stuck trying to compile BepInEx.Bootstrap.dll with the following errors:
Bootstrap/Chainloader.cs(29,17): error CS0246: The type or namespace name 'GameObject' could not be found (are you missing a using directive or an assembly reference?) 
Logging/UnityLogWriter.cs(64,90): error CS0246: The type or namespace name 'LogType' could not be found (are you missing a using directive or an assembly reference?) 
Contract/BaseUnityPlugin.cs(8,45): error CS0246: The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)

MonoBehaviour Is found in UnityEngine.dll, but I can't work out how get the linker to find it. The other two are a complete mystery.

Any clues?
//B

**Comment by boinkey** [comment]
Ha, missed the reply from softashell. Thanks, I managed to get the game patched. I think I had to cd to the directory where the io.exe is in order to get the dll to load. May want to check that in case you add it to the wiki. Alas, the patch messed up the game, so now it won't work any longer. 

//B

**Comment by bbepis** [comment]
>MonoBehaviour Is found in UnityEngine.dll, but I can't work out how get the linker to find it. The other two are a complete mystery.

The BepInEx searches for the UnityEngine.dll library to be located in the `/lib` folder alongside 0Harmony.dll and Mono.Cecil.dll. I don't believe there should be any other required dependencies.

>Ha, missed the reply from softashell. Thanks, I managed to get the game patched. I think I had to cd to the directory where the io.exe is in order to get the dll to load. May want to check that in case you add it to the wiki. Alas, the patch messed up the game, so now it won't work any longer.

Yes, that looks like a much better solution. The need to cd to the directory is probably how wine determines which .dll files to override the builtin libraries, instead of using the .exe location.

Do you know the reason for the patch messing up the game? Is it to do with BepInEx, or something else that comes with the patch?

**Comment by denikson** [comment]
@boinkey 

> I think I had to cd to the directory where the io.exe is in order to get the dll to load. 

This might be an issue with IO itself, I recall Doorstop failing if you ran the game through the launcher.
Though, I think the issue is that if you don't `cd` to the game folder, the game will consider the current directory as the working directory, which BepInEx depends on being set correctly. I have a fix for that in Doorstop, but I don't think I ever released it because of its "hacky" nature of manually changing the working directory if it didn't match that of the game.

>May want to check that in case you add it to the wiki. Alas, the patch messed up the game, so now it won't work any longer.

Might elaborate that a bit? You mean the hardpatcher (i.e. the `BepInEx.Patcher`), right? Doorstop-based solution doesn't touch any files so it shouldn't affect the game files.

**Comment by denikson** [comment]
Thanks for all the information! Clearly, this is an issue we all managed to benefit from.

We'll update the wiki with a guide how to setup BepInEx with wine using information obtained from this issue. 

As for the misconfigured BepInEx.Patcher, it is probably just a typo. Will fix it asap.
