### ISSUE TITLE
Crash when H scene

### ISSUE THREAD

**Issue by muufy** [BepInEx/BepInEx#57]
[output_log.txt](https://github.com/BepInEx/BepInEx/files/2674055/output_log.txt)
[error.log](https://github.com/BepInEx/BepInEx/files/2674056/error.log)

**Comment by denikson** [comment]
Greetings!

The main issue for the crash is because the game ran out of free memory:
```
DynamicHeapAllocator allocation probe 1 failed - Could not get memory for large allocation 16734179200.
DynamicHeapAllocator allocation probe 2 failed - Could not get memory for large allocation 16734179200.
DynamicHeapAllocator allocation probe 3 failed - Could not get memory for large allocation 16734179200.
DynamicHeapAllocator allocation probe 4 failed - Could not get memory for large allocation 16734179200.
DynamicHeapAllocator out of memory - Could not get memory for large allocation 16734179200!
Crash!!!
```

That said, you also have a ton of other errors, which might be caused by an outdated game and plug-ins. I suggest getting the latest game updates and update all plugins. If the issue still persists, you should ask help from plugin developers. This repository is purely for core BepInEx, so we can't help with specific plug-ins.

**Comment by denikson** [comment]
Closing this owing to the lack of response. As I stated in the previous message, I suggest contacting the developers of the plugins or getting general help from the game's community.

If you do have any issues related to core BepInEx, please create a new issue.
