### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by emsimpson92** [BepInEx/BepInEx#70]
https://cdn.discordapp.com/attachments/560869442666627094/566723919592292382/mis.png

More information here

**Comment by denikson** [comment]
Greetings!

This issue seems to be related to Risk of Rain 2 and not directly to base BepInEx. As such, I suggest first asking help from the game's community sources (i.e. the [Mod Developer Discord](https://discord.gg/TY9y9XJ)). This is also mentioned in the [contribution guide](https://github.com/BepInEx/BepInEx/blob/master/CONTRIBUTING.md#using-the-issue-tracker) of this project -- please read it (or at least skim through it) before posting any issues.

If you will not be able to get support there, please make a new, more detailed issue (by using one of the provided templates).

P.S. From what I know, RoR 2 prevents you from matching up with players that have a modded game. This is done by setting a special `isModded` switch in the game that will mark your game as modded (and make your game version to be `MOD`).
