### ISSUE TITLE
Seems to no longer allow multiplayer with Bepinex preloaded

### ISSUE THREAD

**Issue by thisandthatXD** [BepInEx/BepInEx#72]
**Describe the bug**

**To Reproduce**
A short description of what you did for the bug to happen.

**Expected behavior**

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
 - BepInEx version [e.g. 4.0]: 

**Additional context**

**Comment by denikson** [comment]
Greetings!

This issue seems to be related to Risk of Rain 2 and not directly to base BepInEx. As such, I suggest first asking help from the game's community sources (i.e. the [Mod Developer Discord](https://discord.gg/TY9y9XJ)). This is also mentioned in the [contribution guide](https://github.com/BepInEx/BepInEx/blob/master/CONTRIBUTING.md#using-the-issue-tracker) of this project -- please read it (or at least skim through it) before posting any issues.

If you will not be able to get support there, please make a new, more detailed issue (**by actually filling in the provided template**).

P.S. From what I know, RoR 2 prevents you from matching up with players that have a modded game. This is done by setting a special `isModded` switch in the game that will mark your game as modded (and make your game version to be `MOD`).
