### ISSUE TITLE
Problem executable_name for Linux lethal company

### ISSUE THREAD

**Issue by grazyping** [BepInEx/BepInEx#723]
### What happened?

I have a problem running the script for Lethal Company, I drag all the files into the directory, insert the name of the executable file, but it gives me the error that this is a Windows file and I need to download a mod for windows.

### Steps to reproduce

I'm unpacking to the root folder of the game
I add the name of the executable file
executable_name="Lethal Company.exe"
I run the script but it gives the following error
sh ./run_bepinex.sh 
/home/grazyping/.local/share/Steam/steamapps/common/Lethal Company/Lethal Company.exe
The executable is a Windows executable file. You must use Wine/Proton and BepInEx for Windows with this executable.
Uninstall BepInEx for *nix and install BepInEx for Windows instead.
More info: https://docs.bepinex.dev/articles/advanced/steam_interop.html#protonwine
There are no x86_64 executables in this game, and I don't understand how to make this script work with this game, especially through steam. This game was bought from me

### BepInEx Distribution

Stable from GitHub

### Environment

```markdown
- OS: Debian 12
- BepInEx: 5.4.22
- Game: lethal company
```

**Comment by toebeann** [comment]
That's because you DO need the windows version of BepInEx. It's a windows game running under an emulator on Linux, and you need to run bepinex under the emulator too. So you need to follow the instructions for running with steam via proton. The Unix one is for games that are compiled as native Linux/macOS executables, which Lethal Company is not.
