### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by MingoDeMango** [BepInEx/BepInEx#76]
whenever i try to load a mod i get an error message "MissingMethodException" it you do see this i would probably see it sooner on my discord @MingoDeMago.

thanks

**Comment by denikson** [comment]
Greetings!

Thank you for posting this! However, please use a proper issue template, so it's a bit simpler for us to understand your issue, what game version you're running and what the exact problem is. As such, please refer to the [contribution guide](https://github.com/BepInEx/BepInEx/blob/master/CONTRIBUTING.md#bug-reports) on what to include in the issue.

Unfortunately it is difficult to provide any help without any exact log, screenshot or a description of what you did. We want to keep the issues centralized here as much as possible, since it helps us keep track of all the problems.

All in all, I'm closing this issue as lacking. If you have an issue you want to report or have any help with, please create a new issue and relay *all the information you know*. Consider using an issue template, as it lays out exactly what information you should provide.
