### ISSUE TITLE
BepInEx 5 Plugin Templates Fail to Create

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [BepInEx/BepInEx#778]
### What happened?

Bepinex 5 is correctly installed as well as the templates for that version, but running the command for a Mono net 3.5 game `dotnet new bepinex5plugin -n TestPlugin -T net35 -U 5.6.7.15207619` errors with a null reference. Not sure if there's any way to get more info on this.

I've also tried net46 and bleeding edge (which would fail to install with some Harmony error) with no luck.

Through some research, it seems to be an issue with .NET 8 which I have, but I'd really rather not downgrade if I can avoid it.

### BepInEx Distribution

Stable from GitHub

### Log outputs

```txt
Template "BepInEx 5 Plugin Template" could not be created.
Failed to create template.
Details: Object reference not set to an instance of an object.
```

### Environment

```markdown
- OS: Windows 10.0.19045
- BepInEx: 5.4.22
- Game: Ittle Dew 2
```

**Comment by Chris-Is-Awesome** [comment]
Got question answered on Discord, .NET broke template creation.

**Comment by tonebacas** [comment]
> Got question answered on Discord, .NET broke template creation.

What did you do to get it working?

**Comment by Chris-Is-Awesome** [comment]
> > Got question answered on Discord, .NET broke template creation.
> 
> What did you do to get it working?

The template was lacking .NET 8 support until [this PR](https://github.com/BepInEx/BepInEx.Templates/pull/12) was merged, so using template now should work with .NET 8. If not, you can downgrade, use template, then go back to 8, which is what I did before PR.

**Comment by toebeann** [comment]
> > Got question answered on Discord, .NET broke template creation.
> 
> What did you do to get it working?
> 
> 
> 

It's because you have the .NET 8 SDK installed and the template isn't compatible with it unfortunately, apparently due to a regression in .NET.

The workaround for now is to add a `global.json` file in the folder specifying which dotnet SDK version to use (6 or 7 is fine) like so:

1. First make sure you have an earlier dotnet SDK version installed. Go download and install one if unsure.
2. Get the exact dotnet sdk version number you wanna use by listing them out and picking 6 or 7:
```dotnet --list-sdks```
3. Now create a global.json in the folder where you want to run the template:
```dotnet new globaljson --sdk-version [full sdk version number]```

Now you should be able to run the BepInEx template from that folder without issue.

**Comment by p4nu** [comment]
As of today I can confirm that plugin template is not working in the stable template branch. I used a bleeding edge template for BepInEx for making template in dotnet 8

**Comment by t-tiktok** [comment]
not work
