### ISSUE TITLE
Game stutters about every second or two

### ISSUE THREAD

**Issue by Krizzen** [BepInEx/BepInEx#93]
Self explanatory bug. Latest Bepinex as of 9/21/2019, no mods at all.

Any chance for a fix, or are we doomed to stutter for mod support?

Thanks!

**Comment by denikson** [comment]
Greetings!

Unfortunately this is anything but self-explanatory -- if it were, we would've noticed it too. It would be of utmost benefit to us if you used one of the provided issue templates and elaborated on your issue.
Most importantly, we always want to know the following:

* What game are you using BepInEx on?
* What did you try to do?
* Any patchers or plugins installed?
* Any errors in the console?

As BepInEx is designed to be game-agnostic, explaining your current setup in detail is helpful for us to understand how to reproduce the issue.

**Comment by Krizzen** [comment]
Sorry, I didn't realize BepInEx was a generic game patcher... I know, it's obvious, but I was frustrated.

- What game are you using BepInEx on?

Risk of Rain 2

- What did you try to do?

Run the game with this [BepInEx pack]](https://thunderstore.io/package/bbepis/BepInExPack/)

- Any patchers or plugins installed?

From the console log:

2 patcher plugin(s) loaded
1 plugin loaded R2API 2.1.11

- Any errors in the console?

No.


Notice, the BepInEx pack I linked includes 1 patcher, and the single plugin I downloaded includes a patcher as well. After further testing, it appears I have no stutter with 0 plugins.

Perhaps there's a memory leak triggering the GC from the patcher? Could elevating the logging level reveal some insight to the problem?

Please excuse my elementary understanding of this project.

Thanks!

**Comment by denikson** [comment]
Thank you for the information!

At this moment the issue is known to the RoR2 community. The problem seems to be caused by MonoMod's `MMHOOK` DLL that plugins use to patch the game's functionalities. The DLL is specific to RoR2 and it's not part of base BepInEx. However, the version of BepInEx available on Thunderstore is shipped with it for the convenience of modders.

At this moment the problem is being investigated in RoR2 community and I suggest you look for support and possible answers to your stuttering problem there. That said, the upcoming version of BepInEx might provide a fix for loading large DLL files -- like `MMHOOK`.

**Comment by Krizzen** [comment]
Perfect. Thanks so much. Awesome project by the way!
