### ISSUE TITLE
AI-Shoujo day-1 update crashes on startup 90% of the time

### ISSUE THREAD

**Issue by PolarManne** [BepInEx/BepInEx#95]
**Describe the bug**
The game crashes shortly after being started (before the Illusion logo appears). Occasionally it will successfully startup, but most of the time it doesn't.

**To Reproduce**
Start the game.

**Expected behavior**
Not crashing.

**Screenshots and logs**
[LogOutput.log](https://github.com/BepInEx/BepInEx/files/3772395/LogOutput.log)

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: AI-Shoujo v1.0.1
 - BepInEx version [e.g. 4.0]: 5.0.0.161

**Additional context**

**Comment by denikson** [comment]
Greetings!

This issue is known and appears to be exactly the same as in #91.  
After some testing, the issue is indeed fixed after you [do as instructed in the aforementioned issue](https://github.com/BepInEx/BepInEx/issues/91#issuecomment-526892533).

If you still do have the issue after installing MagicCarrot, please reopen this issue.
