### ISSUE TITLE
AISyoujyo can not be controlled after pressing f1

### ISSUE THREAD

**Issue by C4nf3ng** [BepInEx/BepInEx#96]
**Describe the bug**
when pressing f1 which is the menu hot key of the game and also the config menu hot key of BepInEx. After the config menu of BepInEx pop up, the game screen fixed and can not be controlled any more.
**To Reproduce**
A short description of what you did for the bug to happen.
pressing f1 in the game
**Expected behavior**

**Screenshots and logs**
Include a console log (`output_log.txt` and/or `preloader_xxx_xxx.log`), if the error is visible there.  
If not possible, include a screenshot of the error.

**Desktop (please complete the following information):**
 - Game and game version [e.g. COM3D2 1.15]: 
 - BepInEx version [e.g. 4.0]: 
BepInEx version 5.0.0.0
**Additional context**

**Comment by denikson** [comment]
Greetings!

BepInEx itself does not come with any UI-based configuration managers. My guess is you're using [BepInEx.ConfigurationManager](https://github.com/BepInEx/BepInEx.ConfigurationManager) plug-in that is responsible for this.

As such, please move the issue there since it is not related to core BepInEx.
